In [34]:
# Standard Library Imports
import os  # For file and directory operations
import sys  # For system-specific parameters and functions
import csv  # For CSV file handling
import json  # For JSON file handling
import re  # For regular expressions
import shutil  # For high-level file operations

# Third-Party Library Imports
import numpy as np  # For numerical operations
import matplotlib.pyplot as plt  # For plotting and visualization
import PIL  # For image processing (Pillow library)
import psutil  # For system and process utilities
import PyPDF2  # For PDF file manipulation
import requests  # For HTTP requests
import scienceplots  # For beautiful scientific plots
import sympy as sp  # For symbolic mathematics
import nbmerge  # For merging Jupyter notebooks

# Custom Settings
# Set NumPy print options to show floats with one decimal
np.set_printoptions(precision=1, formatter={'float': '{:.1f}'.format})


<Token var=<ContextVar name='format_options' default={'edgeitems': 3, 'threshold': 1000, 'floatmode': 'maxprec', 'precision': 8, 'suppress': False, 'linewidth': 75, 'nanstr': 'nan', 'infstr': 'inf', 'sign': '-', 'formatter': None, 'legacy': 9223372036854775807, 'override_repr': None} at 0x000001B22DD1D0D0> at 0x000001B23230B180>

In [ ]:
matrix1 = np.array([[-1, 2],
            [4, -8]])

matrix2 = np.array([[4, 6],
            [2, 3]])

result = matrix1 @ matrix2
result


In [ ]:
def calculate_function(x, y):
    """
    Calculates the value of a function defined as a determinant ratio.

    Args:
        x: The first input variable (integer).
        y: The second input variable (integer).

    Returns:
        The calculated function value.
    """
    matrix1 = np.array([[3, x], [2, y]])
    matrix2 = np.array([[2, 6-x-y], [7, 6]])

    return np.linalg.det(matrix1) / np.linalg.det(matrix2)

# Calculate expected values of X and Y
E_X = (3/7) * 6
E_Y = (2/7) * 6

# Calculate covariance
cov_XY = sum(x * y * calculate_function(x, y) for x in range(4) for y in range(4-x)) - E_X * E_Y

# Calculate standard deviations
std_X = np.sqrt(sum((x - E_X)**2 * (3/7) * (6/6) for x in range(4)))
std_Y = np.sqrt(sum((y - E_Y)**2 * (2/7) * (6/6) for y in range(4)))

# Calculate correlation coefficient
correlation_coefficient = cov_XY / (std_X * std_Y)

print("Covariance (cov_XY):", cov_XY)
print("Standard deviation of X (std_X):", std_X)
print("Standard deviation of Y (std_Y):", std_Y)
print("Correlation coefficient:", correlation_coefficient)


In [25]:
data1 = [
    40.83, 39.17, 44.70, 56.26, 83.76, 55.26, 56.99, 46.58, 46.41, 86.82, 44.40, 53.87,
    67.37, 65.71, 34.59, 42.09, 49.15, 60.75, 38.31, 68.31, 36.52, 26.52, 41.24, 50.62,
    48.55, 33.87, 37.67, 34.81, 34.12, 51.09, 72.44, 36.65, 39.42, 35.02, 79.38, 47.46,
    31.92, 79.49, 18.46, 46.60, 57.16, 37.03, 39.81, 77.09, 57.65, 48.08, 40.15, 51.47,
    51.26, 50.47, 39.87, 19.36, 39.32, 45.53, 47.03, 39.30, 19.79, 21.92, 48.70, 56.65,
    49.25, 55.26, 65.32, 52.63, 51.24, 46.47, 46.92, 41.82, 61.26, 71.05, 40.02, 50.98,
    61.54, 46.00, 35.79, 80.88, 49.53, 44.12, 55.04, 58.18, 60.71, 31.09, 55.71, 55.43,
    54.70, 55.51, 32.74, 44.15
]
data2 = [
    50, 35, 0, 45, 0, 85, 40, 15, 45, 65, 15, 60, 45, 50, 35, 50, 75, 80, 45, 95, 
    0, 15, 90, 95, 50, 80, 95, 90, 50, 60, 0, 95, 30, 55, 0, 0, 60, 35, 90, 40, 
    40, 35, 70, 0, 95, 65, 85, 35, 70, 0, 35, 55, 85, 75, 20, 35, 90, 95, 45, 25, 
    0, 55, 0, 45, 20, 45, 60, 70, 30, 65, 70, 30, 40, 85, 90, 35, 40, 75, 40, 90, 
    0, 65, 50, 55, 40, 70, 65, 90, 75, 35, 70, 55, 70
]

# Calculate the mean
mean = sum(data1) / len(data1)

print("The mean is:", mean)
max(data1)

data1_s = sorted(data1, reverse=True)
data2_s = sorted(data1)
count1 = sum(score <= 77.09 for score in data1_s)
count2 = sum(score <= 77.09 for score in data1_s)

perc1 = ((len(data1)-count1+1)/ len(data1)*100)
perc2 = ((len(data2)-count2+1)/ len(data2)*100)

print(f"%{round(perc1,0):.0f}")
print(f"%{round(perc2,0):.0f}")
19/2


The mean is: 48.91090909090909
%7
%12


9.5

In [ ]:
# defining matrixes
C_BV = np.array([0, 20, 60])

B = np.array([[1,1,8], [0,1.5,4], [0,0.5,2]])
B_inv = np.array([[1, 2, -8], [0, 2, -4], [0, -0.5, 1.5]])
B_inv2 = np.linalg.inv(B)

a2 = [6,2,1.5]
s2 = [0, 1, 0]
s3 = [0, 0, 1]

c_2  = 30
c_s2 = 0
c_s3 = 0

# matrix verification
if(np.allclose(B_inv, B_inv2)):
    print("yeeey! Calculated B_inv equals given result.")
    print(B_inv)
else:
    print(":( sadge.")
    print("Calculated B_inv didn't equal the given result. Maybe check the matrixes?")

# multiply
c_hat_2 = (C_BV @ B_inv @ a2) - c_2
c_hat_s2 = (C_BV @ B_inv @ s2) - c_s2
c_hat_s3 = (C_BV @ B_inv @ s3) - c_s3

# results
print("\nprinting results:")
print(c_hat_2)
print(c_hat_s2)
print(c_hat_s3)


yeeey! Calculated B_inv equals given result.
[[1.0 2.0 -8.0]
 [0.0 2.0 -4.0]
 [0.0 -0.5 1.5]]

printing results:
5.0
10.0
10.0


In [2]:
B = np.array([[2,0], [1,1]])
B_inv = np.linalg.inv(B)
print(B_inv)


[[0.5 0.0]
 [-0.5 1.0]]


In [31]:
from sympy import symbols, Matrix

delta = symbols('delta')

A = np.array([[0, 20, 60+delta]])
B = np.array([[1,1,8], [0,1.5,4], [0,0.5,2]])
B_inv = np.linalg.inv(B)
C = A@B_inv
D = np.array([[6], [2], [1.5]])
E = np.array([[0], [1], [0]])
F = np.array([[0], [0], [1]])

C@D - 30

array([[1.25*delta + 5.00000000000001]], dtype=object)

In [ ]:
f2=200
f3=180
f1 = sp.symbols('x')
R=800
234/424
np.degrees(1.983)

np.float64(113.61753077444226)

: 